### ISSUE TITLE
upgrade-downstream plugin does not use generic commit user

### ISSUE THREAD

**Issue by szczepiq** [mockito/shipkit#386]
### Problem

upgrade-downstream plugin makes a commit without setting the user to our generic user ([example](https://github.com/mockito/shipkit-example/pull/91/commits/407825d8ebadb2f359fe2eb108a35441b4be206c)). We should use a generic user so that the commit [looks like this](https://github.com/mockito/shipkit/commit/9329594f171643eef4077a2b70672fe78ec5e004).

### Suggested implementation

TBD.

**Comment by szczepiq** [comment]
This problem has been fixed. The upgrade-downstream uses correct user now: https://github.com/mockito/shipkit/pull/451

**Comment by epeee** [comment]
It looks like we are still not using the generic user, see [commit](https://github.com/mockito/shipkit/pull/466/commits/1a0b3e0dc15e4dbf5289773b3ed9ed6182aed0b3)
I will provide a pr soon.
